#!/usr/bin/env bash
# Generate wiki/Functions-Index.md from the current modules.
#
# Regenerate:
#   ./scripts/gen-function-index.sh
#
# The generated file is a stable, alphabetically-sorted index of every
# top-level function definition under modules/. Hand-maintained wiki
# prose (Functions-Dependencies.md, Module-*.md) is NOT touched.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/wiki/Functions-Index.md"

{
    echo "# Function Index"
    echo
    echo "> Auto-generated by \`scripts/gen-function-index.sh\`. Do not hand-edit."
    echo "> Regenerate after adding or removing module functions; the"
    echo "> conventions linter fails CI if the committed file is stale."
    echo
    echo "One row per top-level function definition. Modules are sorted"
    echo "alphabetically; within each module, functions are listed in"
    echo "their source order. Underscore-prefixed helpers are included."
    echo

    find "$ROOT_DIR/modules" -type f -name '*.zsh' -not -path '*/archived/*' \
        | sort \
        | while IFS= read -r mod; do
            rel="${mod#"$ROOT_DIR"/}"
            echo "## \`$rel\`"
            echo
            grep -E '^[a-zA-Z_][a-zA-Z0-9_]*\(\)' "$mod" \
                | sed -E 's/\(\)[[:space:]]*\{?[[:space:]]*$//' \
                | sed -E 's|^|- `|' \
                | sed -E 's|$|`|' \
                || true
            echo
        done
} > "$OUT"

echo "Wrote $OUT"
